blank_issues_enabled: false

contact_links:
  - name: Questions, Discussions, Ideas
    url: https://github.com/Asaicraft/PropertyBitPack/discussions/new
    about: Please ask and answer questions here.

  - name: PropertyBitPack Community on Discord
    url: https://discord.gg/RpxD2BeNsZ
    about: Join our Discord server to chat with the community.
